# Client's config file

[user]
name  = "Ragnar Lothbrok"
email = "ragnar@kattegat.org"
mode  = "seller"   # "seller" or "buyer", mandatory field


[servers]
  [servers.demo]
  uri = "127.0.0.1:3000"

#  [servers.production]
#  uri = [ "marketplace.io" ]


[wallet]
wallet = "wallet_ragnar.json"


[ledger]
ledger = "ledger_ragnar.json"


[seller]
  api_id = "Z77wU"
  api_key = "P23P7jlDx4RHrmmQsyA23HBhLkWQpp"
  [seller.0]
    name = "Ragnar Lothbrok Stylish Accessories"
    root = "store_ragnar"
