# Client's config file

[user]
name  = "Bob"
email = "bob@somewhere.com"
mode  = "seller"   # "seller" or "buyer", mandatory field


[servers]
  [servers.demo]
  uri = "127.0.0.1:3000"

#  [servers.production]
#  uri = [ "marketplace.io" ]


[wallet]
wallet = "wallet_bob.json"


[ledger]
ledger = "ledger_bob.json"


[seller]
  api_id = "b1V58"
  api_key = "Y1LPzVMDx86HrMxQCyA2sHBMLoaQkj"
  [seller.0]
    name = "Bob's Online Store"
    root = "store_bob"
