# Client's config file

[user]
name  = "James"
email = "james@middleofnowhere.org"
mode  = "seller"   # "seller" or "buyer" or "witness", mandatory field


[marketplace]
uri = "127.0.0.1:43443"


[[rendezvous]]
uri = "/dns4/localhost/tcp/61617/ws/p2p-websocket-star"


[api]
port = 9094


[wallet]
wallet = "wallet.json"


[blockchain]
root = "blockchain"


[purchased]
root = "purchased"


[seller]
  api_id = "n2EPj"
  api_key = "J2NZc67cnJoqrM6R3UCdjhAVfrjXZk"
  [seller.0]
    name = "James @ Cloud Shop"
    root = "store_james"
