# Client's config file

[user]
name  = "CL-2"
email = "cl2@tutova.org"
mode  = "witness"   # "seller" or "buyer" or "witness", mandatory field


[marketplace]
uri = "127.0.0.1:43443"


[[rendezvous]]
uri = "/dns4/localhost/tcp/61617/ws/p2p-websocket-star"


[wallet]
wallet = "wallet.json"


[blockchain]
root = "blockchain"
