# Client's config file

[user]
name  = "Tom"
email = "tom@tom.marketplace.com"
mode  = "seller"   # "seller" or "buyer" or "witness", mandatory field


[marketplace]
uri = "127.0.0.1:43443"


[[rendezvous]]
uri = "/dns4/localhost/tcp/61617/ws/p2p-websocket-star"


[api]
port = 9093


[wallet]
wallet = "wallet.json"


[blockchain]
root = "blockchain"


[purchased]
root = "purchased"


[seller]
  api_id = "Z77wU"
  api_key = "P23P7jlDx4RHrmmQsyA23HBhLkWQpp"
  [seller.0]
    name = "Tom's Digital Store"
    root = "store_tom"
