# Client's config file

[user]
name  = "Alice"
email = "alice@wonderland.com"
mode  = "buyer"   # "seller" or "buyer", mandatory field


[servers]
  [servers.demo]
  uri = "127.0.0.1:3000"

#  [servers.production]
#  uri = [ "marketplace.io" ]


[wallet]
wallet = "wallet.json"


[latest]
latest = "latest.json"


[ledger]
ledger = "blockchain/private"
