# Client's config file

[user]
name  = "Alice"
email = "alice@wonderland.com"
mode  = "buyer"   # "seller" or "buyer" or "witness", mandatory field


[marketplace]
uri = "127.0.0.1:43443"


[[rendezvous]]
uri = "/dns4/localhost/tcp/61617/ws/p2p-websocket-star"


[api]
port = 9091


[wallet]
wallet = "wallet.json"


[blockchain]
root = "blockchain"


[purchased]
root = "purchased"
