# Client's config file

[user]
name  = "Bob"
email = "bob@somewhere.com"
mode  = "seller"   # "seller" or "buyer" or "witness", mandatory field


[marketplace]
uri = "127.0.0.1:3000"


[[rendezvous]]
uri = "/dns4/localhost/tcp/9090/ws/p2p-websocket-star"


[wallet]
wallet = "wallet.json"


[latest]
latest = "latest.json"


[ledger]
ledger = "blockchain/private"


[seller]
  api_id = "b1V58"
  api_key = "Y1LPzVMDx86HrMxQCyA2sHBMLoaQkj"
  [seller.0]
    name = "Bob's Online Store"
    root = "store_bob"
