# Client's config file

[user]
name  = "Bob"
email = "bob@somewhere.com"
mode  = "seller"   # "seller" or "buyer" or "witness", mandatory field


[marketplace]
uri = "127.0.0.1:43443"


[[rendezvous]]
uri = "/dns4/localhost/tcp/61617/ws/p2p-websocket-star"


[api]
port = 9092


[wallet]
wallet = "wallet.json"


[blockchain]
root = "blockchain"


[purchased]
root = "purchased"


[seller]
  api_id = "b1V58"
  api_key = "Y1LPzVMDx86HrMxQCyA2sHBMLoaQkj"
  [seller.0]
    name = "Bob's Online Store"
    root = "store_bob"
