#
# Marketplace protocol
#

# TODO: do we need to sync "PROTO_VERSION" with package.json's "version"?
PROTO_VERSION = "0.0.13"


PROTO_GET_MY_INFO =         "/info/#{PROTO_VERSION}"
PROTO_WHORU =               "/whoru/#{PROTO_VERSION}"

# private ledger's messages
PROTO_GET_ALL_PRIVATE_TXS = "/priv/#{PROTO_VERSION}"
PROTO_PURCHASE1 =            "/purchase1/#{PROTO_VERSION}"
PROTO_PURCHASE2 =            "/purchase2/#{PROTO_VERSION}"
PROTO_PURCHASE3 =            "/purchase3/#{PROTO_VERSION}"
PROTO_PURCHASE4 =            "/purchase4/#{PROTO_VERSION}"
PROTO_PURCHASE5 =            "/purchase5/#{PROTO_VERSION}"
PROTO_PURCHASE6 =            "/purchase8/#{PROTO_VERSION}"
PROTO_PURCHASE8 =            "/purchase6/#{PROTO_VERSION}"
PROTO_PURCHASE7 =            "/purchase7/#{PROTO_VERSION}"
PROTO_TRANSFER1 =            "/transf1/#{PROTO_VERSION}"
PROTO_TRANSFER2 =            "/transf2/#{PROTO_VERSION}"
PROTO_TRANSFER_WEB1 =        "/transfweb1/#{PROTO_VERSION}"
PROTO_TRANSFER_WEB2 =        "/transfweb2/#{PROTO_VERSION}"
PROTO_TRANSFER_WEB3 =        "/transfweb3/#{PROTO_VERSION}"

# public blockchain's messages
PROTO_SYNC_TX =             "/sync/#{PROTO_VERSION}"
PROTO_GET_ALL_PUBLIC_TXS =  "/pub/#{PROTO_VERSION}"
PROTO_GET_PURCHASED =       "/purchased/#{PROTO_VERSION}"
PROTO_BOOTSTRAP =           "/bootstrap/#{PROTO_VERSION}"

module.exports = 
  PROTO_GET_MY_INFO:     PROTO_GET_MY_INFO
  PROTO_WHORU:        PROTO_WHORU
  PROTO_GET_ALL_PRIVATE_TXS: PROTO_GET_ALL_PRIVATE_TXS
  PROTO_GET_ALL_PUBLIC_TXS:  PROTO_GET_ALL_PUBLIC_TXS
  PROTO_SYNC_TX:       PROTO_SYNC_TX
  PROTO_PURCHASE1:     PROTO_PURCHASE1
  PROTO_PURCHASE2:     PROTO_PURCHASE2
  PROTO_PURCHASE3:     PROTO_PURCHASE3
  PROTO_PURCHASE4:     PROTO_PURCHASE4
  PROTO_PURCHASE5:     PROTO_PURCHASE5
  PROTO_PURCHASE6:     PROTO_PURCHASE6
  PROTO_PURCHASE8:     PROTO_PURCHASE8
  PROTO_PURCHASE7:     PROTO_PURCHASE7
  PROTO_GET_PURCHASED: PROTO_GET_PURCHASED
  PROTO_BOOTSTRAP:     PROTO_BOOTSTRAP
  PROTO_TRANSFER1:     PROTO_TRANSFER1
  PROTO_TRANSFER2:     PROTO_TRANSFER2  
  PROTO_TRANSFER_WEB1: PROTO_TRANSFER_WEB1
  PROTO_TRANSFER_WEB2: PROTO_TRANSFER_WEB2
  PROTO_TRANSFER_WEB3: PROTO_TRANSFER_WEB3
