# Client's config file

[user]
name  = "CL-1"
email = "cl1@tutova.org"
mode  = "witness"   # "seller" or "buyer" or "witness", mandatory field


[marketplace]
uri = "127.0.0.1:3000"


[[rendezvous]]
uri = "/dns4/localhost/tcp/9090/ws/p2p-websocket-star"
[[rendezvous]]
uri = "/dns4/ws-star-signal-4.servep2p.com/tcp/443/wss/p2p-websocket-star"


[wallet]
wallet = "wallet.json"


[latest]
latest = "latest.json"


[ledger]
ledger = "blockchain/private"
